
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: 'a'
  password: 'yu'
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: flint_development
test:
  <<: *default
  database: my_database_test

production:
  <<: *default
  database: flint_production